steps:
  - label: "run unit tests"
    agents:
      container_image: ubuntu-2204-ci
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild test
  - label: ":shipit: build and export container, manifests tar files"
    agents:
      container_image: ubuntu-2204-ci
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild build
      - ./scripts/cibuild export_container "${BUILDKITE_PIPELINE_SLUG}_${BUILDKITE_BUILD_NUMBER}.tar" "docker.greymatter.io/development/gm-operator:latest"
      - ./scripts/cibuild export_manifests "${BUILDKITE_PIPELINE_SLUG}_${BUILDKITE_BUILD_NUMBER}_manifests.tar.gz"
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
  - wait
  - trigger: "launch-k3s-buildkite"
    label: "buildkite for default integration tests"
    build:
      env:
        INTEGRATION_TEST_CASE: "default"

  - trigger: "launch-k3s-buildkite"
    label: "buildkite for with_spire integration tests"
    build:
      env:
        INTEGRATION_TEST_CASE: "with_spire"
  - label: "Generate integration test steps that run on ephemeral ec2s"
    commands:
      - ./scripts/cibuild generate_integration_tests default
      - ./scripts/cibuild generate_integration_tests with_spire
    agents:
      container_image: ubuntu-2204-ci
  - wait
  - label: "release"
    agents:
      container_image: ubuntu-2204-ci
    command: "./scripts/cibuild release"
