steps:
  - label: "run unit tests"
    agents:
      container_image: ubuntu-2204-ci
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild test
  - label: ":shipit: build"
    agents:
      container_image: ubuntu-2204-ci
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild build
      - ./scripts/cibuild export_container "quay.io/greymatterio/operator:latest"

      - ./scripts/cibuild export_manifests "${BUILDKITE_PIPELINE_SLUG}_${BUILDKITE_BUILD_NUMBER}_manifests.tar.gz"
  - label: "Build debug container"
    agents:
      container_image: ubuntu-2204-ci
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild build_debug
      - ./scripts/cibuild export_container "quay.io/greymatterio/operator:debug-latest" "debug"
  - wait
  - label: "run integration tests"
    commands:
      - ./scripts/cibuild generate_integration_tests
    agents:
      container_image: ubuntu-2204-ci
  - wait
  - label: "release"
    if: "build.branch == 'main' || build.tag != null"
    agents:
      container_image: ubuntu-2204-ci
    command: "./scripts/cibuild release"
