agents:
  queue: default
  container_image: ubuntu-2204-ci

steps:
  - label: "Scheduled build"
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild build
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
