agents:
  queue: default
  container_image: ubuntu-2204-ci

steps:
  - label: "run unit tests"
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild test
  - label: ":shipit: build"
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild build
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
  - wait
  - label: "run integration tests"
    commands:
      - ./scripts/cibuild generate_integration_tests

